myData <- read.table("household_power_consumption.txt", header = TRUE, sep =";", na.strings = "?")
myData$Date <- as.Date(myData$Date, "%d/%m/%Y")
myData1 <- subset(myData, Date == as.Date("2007-02-01"))
myData2 <- subset(myData, Date == as.Date("2007-02-02"))
myData <- rbind(myData1, myData2)
myData$DateTime <- strptime(paste(myData$Date, myData$Time), "%Y-%m-%d %H:%M:%S")
with(myData, plot(DateTime, Sub_metering_1, main = "", type = "l", xlab = "", ylab = "Energy sub metering"))
with(myData, lines(DateTime, Sub_metering_2, col = "blue"))
with(myData, lines(DateTime, Sub_metering_3, col = "red"))
legend("topright", pch = 19, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, "plot3.png")
dev.off()