myData <- read.table("household_power_consumption.txt", header = TRUE, sep =";", na.strings = "?")
myData$Date <- as.Date(myData$Date, "%d/%m/%Y")
myData1 <- subset(myData, Date == as.Date("2007-02-01"))
myData2 <- subset(myData, Date == as.Date("2007-02-02"))
myData <- rbind(myData1, myData2)
myData$DateTime <- strptime(paste(myData$Date, myData$Time), "%Y-%m-%d %H:%M:%S")
with(myData, plot(DateTime, Global_active_power, main = "", type = "l", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.copy(png, "plot2.png")
dev.off()